/*
 * This source file was generated by the Gradle 'init' task
 */
package heap.dump.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.File;
import java.io.IOException;

public class AppTest {
    @Test public void testMain() throws IOException {
        File heapDump = new File("heap.hprof");
        if (heapDump.exists()) {
            App.main(new String[]{"heap.hprof"});
            // No exception should be thrown
            assertTrue(true);
        } else {
            System.out.println("Skipping testMain: heap.hprof not found.");
        }
    }
}
